Numpy's most useful feature is n dimentional array object: ndarray

In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])

In [4]:
a

array([1, 2, 3])

In [5]:
a[0]

1

In [6]:
a[1]

2

## List vs ndarray

In [4]:
import numpy as np
import time
import sys

In [5]:
l = range(1000)
print(sys.getsizeof(5) * len(l))

28000


In [6]:
array = np.arange(1000)
print(array.size*array.itemsize)

8000


In [37]:
SIZE = 10000000

In [38]:
l1 = range(SIZE)
l2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

In [39]:
# python list
start = time.time()
result = [(x*y) for x, y in zip(l1, l2)]
print("python list took: ", (time.time() - start) * 1000)

# python array
start = time.time()
result = a1 + a2
print("numpy took: ", (time.time() - start) * 1000)

python list took:  610.7254028320312
numpy took:  106.29796981811523


In [40]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
a1 + a2

array([5, 7, 9])

In [41]:
a2 - a1

array([3, 3, 3])

In [42]:
a1 / a2

array([0.25, 0.4 , 0.5 ])