In [3]:
import numpy as np

In [5]:
a = np.array([5, 6, 9])

In [8]:
a[0]

5

In [9]:
a[1]

6

In [10]:
a = np.array([[1, 2], [3, 4], [5, 6]])

In [11]:
a.ndim

2

In [12]:
a = np.array([5, 6, 9])

In [13]:
a.ndim

1

In [14]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a.ndim

2

In [15]:
a.itemsize

8

In [16]:
a.dtype

dtype('int64')

In [18]:
a = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.float64)

In [20]:
a.itemsize

8

In [21]:
# number of element
a.size

6

In [22]:
# show dimension
a.shape

(3, 2)

In [23]:
# it means 3 rows and 2 columns

In [25]:
a = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.complex_)

In [26]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [27]:
# array of zeors
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
# array of ones
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
np.ones((3, 4), dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [32]:
l = range(5)

In [33]:
l

range(0, 5)

In [35]:
l[0]

0

In [36]:
l[1]

1

In [37]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [39]:
# step like list
np.arange(1, 5, 2)

array([1, 3])

In [40]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [41]:
np.linspace(1, 5, 5)

array([1., 2., 3., 4., 5.])

In [42]:
np.linspace(1, 5, 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [44]:
np.linspace(1, 5, 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [45]:
a = np.array([[1, 2], [3, 4], [5, 6]])

In [46]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
a.shape

(3, 2)

In [48]:
a.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
a.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [50]:
# to flatten
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [52]:
# The original still the same
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
# mathematical function in numpy
a.min()

1

In [55]:
a.max()

6

In [56]:
a.sum()

21

![axis](axis.png)

In [57]:
a.sum(axis=0)

array([ 9, 12])

In [58]:
a.sum(axis=1)

array([ 3,  7, 11])

In [60]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [61]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
np.std(a)

1.707825127659933

In [63]:
a = np.array([[1, 2], [3, 4]])

In [64]:
b = np.array([[6, 6], [7, 8]])

In [65]:
a

array([[1, 2],
       [3, 4]])

In [66]:
b

array([[6, 6],
       [7, 8]])

In [67]:
a + b

array([[ 7,  8],
       [10, 12]])

In [68]:
a - b

array([[-5, -4],
       [-4, -4]])

In [69]:
a * b

array([[ 6, 12],
       [21, 32]])

In [70]:
a / b

array([[0.16666667, 0.33333333],
       [0.42857143, 0.5       ]])

In [71]:
a.dot(b)

array([[20, 22],
       [46, 50]])