In [1]:
import numpy as np

### 1. Indexing and slicing

In [2]:
n = [6, 7, 8]

In [3]:
n[0:2]

[6, 7]

![slice](slice.png)

In [6]:
n[-1]

8

In [7]:
a = np.array([6, 7, 8])

In [8]:
a[0:2]

array([6, 7])

In [9]:
a[-1]

8

In [10]:
a = np.array([[6, 7, 8], [1, 2, 3], [9, 3, 2]])

In [11]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [13]:
# row 1 column 2
a[1,2]

3

![slice](slice2.png)

In [14]:
a[0:2, 2]

array([8, 3])

In [15]:
a[-1]

array([9, 3, 2])

In [16]:
a[-1, 0:2]

array([9, 3])

In [18]:
a[:, 1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

### 2. Iterating through arrays

In [19]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [20]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [21]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


### 3. Stacking tocether two arrays

In [23]:
a = np.arange(6).reshape(3,2)

In [24]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [25]:
b = np.arange(6, 12).reshape(3,2)

In [26]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [28]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [29]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [30]:
a = np.arange(30).reshape(2, 15)

In [31]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [32]:
np.hsplit(a, 3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [33]:
result = np.hsplit(a, 3)

In [34]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [35]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [36]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [40]:
result = np.vsplit(a,2)

In [41]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [42]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

### 4. Intdexing with boolean arrays

In [43]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
b = a > 4

In [49]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [50]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [51]:
a[b] = -1

In [52]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])