In [7]:
import numpy as np

In [8]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [10]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [11]:
for x in np.nditer(a, order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [12]:
for x in np.nditer(a, order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [13]:
for x in np.nditer(a, flags=['external_loop'], order='F'):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [14]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * x

In [15]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [16]:
x

array(121)

In [21]:
b = np.arange(3, 19, 5).reshape(4, 1)
b

array([[ 3],
       [ 8],
       [13],
       [18]])

In [22]:
for x,y in np.nditer([a,b]):
    print(x,y)

ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 